In [1]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
print(type(ary))

<class 'numpy.ndarray'>


In [2]:
#创建
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
b = np.arange(0,5,1)
print(b)

[0 1 2 3 4]


In [4]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
#shape属性
ary = np.array([1, 2, 3, 4, 5, 6])
print(type(ary), ary, ary.shape)
#二维数组
ary = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(type(ary), ary, ary.shape)

<class 'numpy.ndarray'> [1 2 3 4 5 6] (6,)
<class 'numpy.ndarray'> [[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [7]:
#dtype
ary = np.array([1, 2, 3, 4, 5, 6])
print(type(ary), ary, ary.dtype)
#转换ary元素的类型
b = ary.astype(float)
print(type(b), b, b.dtype)
#转换ary元素的类型
c = ary.astype(str)
print(type(c), c, c.dtype)

<class 'numpy.ndarray'> [1 2 3 4 5 6] int32
<class 'numpy.ndarray'> [1. 2. 3. 4. 5. 6.] float64
<class 'numpy.ndarray'> ['1' '2' '3' '4' '5' '6'] <U11


In [8]:
#size
ary = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
#观察维度，size，len的区别
print(ary.shape, ary.size, len(ary))

(2, 4) 8 2


In [9]:
#数组元素索引
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(a,a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


In [10]:
print(a[0])

[[1 2]
 [3 4]]


In [11]:
print(a[0][0])

[1 2]


In [12]:
print(a[0][0][0])

1


In [13]:
print(a[0,0,0])

1


In [14]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            print(a[i,j,k])

1
2
3
4
5
6
7
8


In [15]:
#自定义复合类型
data=[
    ('zssss', [90, 80, 85], 15),
    ('lsss', [92, 81, 83], 16),
    ('ww', [95, 85, 95], 15)
]
#第一种设置dtype的方式
a = np.array(data, dtype='U3, 3int32, int32')
print(a)
print(a[0]['f0'], ":", a[1]['f1'])
print(a[0].dtype)
print(a[1][1])

[('zss', [90, 80, 85], 15) ('lss', [92, 81, 83], 16)
 ('ww', [95, 85, 95], 15)]
zss : [92 81 83]
[('f0', '<U3'), ('f1', '<i4', (3,)), ('f2', '<i4')]
[92 81 83]


In [16]:
#第二种设置dtype的方式
b = np.array(data, dtype=[('name', 'str_',2),
                    ('scores', 'int32', 3),
                    ('age', 'int32', 1)])
print(b[0]['name'], ":", b[0]['scores'])

zs : [90 80 85]


C:\Users\40011\AppData\Local\Temp\ipykernel_23472\3455662303.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  b = np.array(data, dtype=[('name', 'str_',2),


In [17]:
#第三种设置dtype的方式
c = np.array(data, dtype={'names': ['name', 'scores', 'ages'],
                    'formats': ['U3', '3int32', 'int32']})
print(c[0]['name'], ":", c[0]['scores'], ":", c.itemsize)

zss : [90 80 85] : 28


In [18]:
#第四种设置dtype的方式  
d = np.array(data, dtype={'name': ('U3', 0),#U3代表最多能放3个字符
                          #字节偏移量，默认到底是不是对其不清楚，
                    'scores': ('3int32', 12),
                    'age': ('int32', 24)})
print(d[0]['name'], d[0]['scores'], d.itemsize)
                    #itemsize代表一个元素的字节数大小

zss [90 80 85] 28


In [19]:
#测试日期类型数组
f = np.array(['2011', '2012-01-01', '2013-01-01 01:01:01','2011-02-01'])
f = f.astype('M8[D]')
print(f)
f = f.astype('i4')
print(f)
print(f[3]-f[0])
f.astype('bool')

['2011-01-01' '2012-01-01' '2013-01-01' '2011-02-01']
[14975 15340 15706 15006]
31


array([ True,  True,  True,  True])

In [20]:
#视图变维-数据是共享的
a = np.arange(1, 9)
print(a)  # [1 2 3 4 5 6 7 8]
b = a.reshape(2, 4)	#视图变维  : 变为2行4列的二维数组
print(b)
c = b.reshape(2, 2, 2) #视图变维    变为2页2行2列的三维数组
print(c)
d = c.ravel()#视图变维 变为1维数组
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [21]:
#复制变维-数据独立
e = c.flatten()
print(e)
a += 10
print(a, e, sep='\n')

[1 2 3 4 5 6 7 8]
[11 12 13 14 15 16 17 18]
[1 2 3 4 5 6 7 8]


In [22]:
#就地变维：直接改变原数组对象的维度，不返回新数组
a.shape = (2, 4)
print(a)
a.resize(2, 2, 2)
print(a)

[[11 12 13 14]
 [15 16 17 18]]
[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [23]:
#一维数组切片
a = np.arange(1, 10)
print(a)  # 1 2 3 4 5 6 7 8 9
print(a[:3])  # 1 2 3
print(a[3:6])   # 4 5 6
print(a[6:])  # 7 8 9
print(a[::-1])  # 9 8 7 6 5 4 3 2 1
print(a[:-4:-1])  # 9 8 7
print(a[-4:-7:-1])  # 6 5 4
print(a[-7::-1])  # 3 2 1
print(a[::])  # 1 2 3 4 5 6 7 8 9
print(a[:])  # 1 2 3 4 5 6 7 8 9
print(a[::3])  # 1 4 7
print(a[1::3])  # 2 5 8
print(a[2::3])  # 3 6 9

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]
[9 8 7 6 5 4 3 2 1]
[9 8 7]
[6 5 4]
[3 2 1]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7]
[2 5 8]
[3 6 9]


In [24]:
#多维数组切片
a = np.arange(1, 28)
a.resize(3,3,3)
print(a)
print('-----------------')
#切出1页 
print(a[1, :, :])
print('-----------------')
#切出所有页的1行
print(a[:, 1, :])
print('-----------------')
#切出0页的1行1列
print(a[0, :, 1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
-----------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]
-----------------
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]
-----------------
[2 5 8]


In [25]:
#掩码操作
a = np.arange(1, 10)
mask = [True, False,True, False,True, False,True, False,True]
print(a[mask])

[1 3 5 7 9]


In [26]:
#多维数组组合拆分-垂直方向
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a, b))
print(c)
# 垂直方向完成拆分操作，生成两个数组
d, e = np.vsplit(c, 2)
print(d)
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [27]:
#多维数组组合拆分-水平方向
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
# 水平方向完成组合操作，生成新数组 
c = np.hstack((a, b))
print(c)
# 水平方向完成拆分操作，生成两个数组
d, e = np.hsplit(c, 2)
print(d)
print(e)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [28]:
#多维数组组合拆分-深度方向
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
# 深度方向（3维）完成组合操作，生成新数组
i = np.dstack((a, b))
print(i)
# 深度方向（3维）完成拆分操作，生成两个数组
k, l = np.dsplit(i, 2)
print(k)
print(l)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [29]:
#长度不等的数组组合
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4])
# 填充b数组使其长度与a相同
b = np.pad(b, pad_width=(0, 1), mode='constant', constant_values=-1)
print(b)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a, b))
print(c)

[ 1  2  3  4 -1]
[[ 1  2  3  4  5]
 [ 1  2  3  4 -1]]


In [30]:
#简单一维数组组合方案
a = np.arange(1,9)#[1, 2, 3, 4, 5, 6, 7, 8]
b = np.arange(9,17)#[9,10,11,12,13,14,15,16]
#把两个数组摞在一起成两行
c = np.row_stack((a, b))
print(c)
#把两个数组组合在一起成两列
d = np.column_stack((a, b))
print(d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]


In [31]:
# ndarray类的其他属性
a = np.array([[1 + 1j, 2 + 4j, 3 + 7j],
              [4 + 2j, 5 + 5j, 6 + 8j],
              [7 + 3j, 8 + 6j, 9 + 9j]])
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.real, a.imag, sep='\n')
print(a.T)
print([elem for elem in a.flat])
b = a.tolist()
print(b)

(3, 3)
complex128
2
9
16
144
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1.+1.j 4.+2.j 7.+3.j]
 [2.+4.j 5.+5.j 8.+6.j]
 [3.+7.j 6.+8.j 9.+9.j]]
[(1+1j), (2+4j), (3+7j), (4+2j), (5+5j), (6+8j), (7+3j), (8+6j), (9+9j)]
[[(1+1j), (2+4j), (3+7j)], [(4+2j), (5+5j), (6+8j)], [(7+3j), (8+6j), (9+9j)]]
