# How to import NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[1 2 3 4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# More information about arrays

nothing should be noted

# How to create a basic array

In [3]:
np.zeros(2)

array([0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [5]:
np.empty(3)

array([4.24399158e-314, 8.48798317e-314, 1.27319747e-313])

In [6]:
np.arange(1,5)

array([1, 2, 3, 4])

In [7]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [8]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.ones(2,dtype=np.int64)

array([1, 1], dtype=int64)

# Adding, removing, and sorting elements

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

In [13]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [14]:
array_example.ndim

3

In [15]:
array_example.size

24

In [16]:
array_example.shape

(3, 2, 4)

# Can you reshape an array?

In [17]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

np.reshape(a, newshape=(1, 6), order='C')

[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

(6,)


In [19]:
a2 = a[np.newaxis, :]
print(a2,a2.ndim)
a2.shape

[[1 2 3 4 5 6]] 2


(1, 6)

In [20]:
row_vector = a[np.newaxis, :]
print(row_vector)
row_vector.shape

[[1 2 3 4 5 6]]


(1, 6)

In [21]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [22]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [23]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and slicing

In [24]:
data = np.array([1,2,3])

In [25]:
data[1]

2

In [26]:
data[0:2]

array([1, 2])

In [27]:
data[1:]

array([2, 3])

In [28]:
data[-2:]

array([2, 3])

In [29]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [30]:
a[a<5]

array([1, 2, 3, 4])

In [31]:
five_up=(a>=5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [33]:
a[(a>2)&(a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
(a>5)| (a==5)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [36]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [37]:
list_of_coordinates = list(zip(b[0],b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [38]:
a[b]

array([1, 2, 3, 4])

# How to create an array from existing data

In [39]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [41]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [42]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [43]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [44]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [46]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [47]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [48]:
b1 = a[0, :]
print(b1)
b1[0] = 99
print(b1)
a

[1 2 3 4]
[99  2  3  4]


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [50]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data+ones

array([2, 3])

In [51]:
data-ones

array([0, 1])

In [52]:
data*data

array([1, 4])

In [53]:
data/data

array([1., 1.])

In [54]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [55]:
b = np.array([[1, 1], [2, 2],[3,4]])
b

array([[1, 1],
       [2, 2],
       [3, 4]])

In [56]:
b.sum(axis=0)

array([6, 7])

In [57]:
b.sum(axis=1)

array([2, 4, 7])

# Broadcasting

In [58]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

# More useful array operations

In [59]:
data.max()

2.0

In [60]:
data.sum()

3.0

In [61]:
data.min()

1.0

In [62]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [63]:
a.sum()

4.8595784

In [64]:
a.min()

0.05093587

In [65]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

# Creating matrices

In [66]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
data[0,1]

2

In [71]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [72]:
data[0:2,0]

array([1, 3])

In [73]:
data.max()

6

In [74]:
data.min()

1

In [75]:
data.sum()

21

In [78]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [79]:
data.max(axis=0)

array([5, 6])

In [81]:
data.max(axis=1)

array([2, 5, 6])

In [82]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data+ones

array([[2, 3],
       [4, 5]])

In [83]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [84]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])